spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/docman_man?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2b8
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 5
  mvc:
    log-request-details: true
#xxl:
#  job:
#    admin:
#      addresses: http://localhost:8080/job-plat
#    executor:
#      ip:
#      port: 9999
#      logpath: /Users/lifuqiang/data/applogs/xxl-job/jobhandler
#      appname: docman-man-job-dev
#    accessToken: